server:
  port: 8888

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.135.174:3306/debt?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 1800000
      connection-test-query: SELECT 1
   # driver-class-name: com.mysql.jdbc.Driver
  #redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
logging:
  level:
    root: info
    com.smart.bracelet: debug
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# security配置
security:
  oauth2:
    client:
      client-id: client
      client-secret: 123456
    resource:
      user-info-uri: http://localhost:8888/api/oauth/checkToken
      prefer-token-info: false
# 图片上传位置
fileImgPath: /root/upload/
#合同存放位置
fileDocx: /root/upload/docFile/